include: package:lint/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  errors:
    invalid_annotation_target: ignore
