name: piton_assignment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cross_connectivity: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  flutter_svg_provider: ^1.0.3
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hooks_riverpod: ^2.1.3
  http: ^0.13.5
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-semiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
